"use strict";var v=Object.defineProperty;var U=Object.getOwnPropertyDescriptor;var z=Object.getOwnPropertyNames;var Q=Object.prototype.hasOwnProperty;var X=(r,t)=>{for(var n in t)v(r,n,{get:t[n],enumerable:!0})},Z=(r,t,n,a)=>{if(t&&typeof t=="object"||typeof t=="function")for(let l of z(t))!Q.call(r,l)&&l!==n&&v(r,l,{get:()=>t[l],enumerable:!(a=U(t,l))||a.enumerable});return r};var tt=r=>Z(v({},"__esModule",{value:!0}),r);var st={};X(st,{default:()=>V});module.exports=tt(st);var e=require("@raycast/api"),o=require("react"),s=require("react/jsx-runtime"),N=["http://air.tail97979c.ts.net:8080/chat/stream","http://100.103.103.57:8080/chat/stream"];function D(r){let t=new Date(r),n=t.getHours().toString().padStart(2,"0"),a=t.getMinutes().toString().padStart(2,"0");return`${n}:${a}`}function et(r,t){let n=[];for(let a of r){let l=a.role==="user"?"You":"Secretary";n.push(`[${l} \xB7 ${D(a.ts)}]`),n.push(a.text),n.push("")}return t&&(n.push("[Secretary \xB7 thinking]"),n.push(`(${t}\u2026)`)),n.join(`
`).trim()||"(new conversation)"}function nt(r){return r.map(t=>`${t.role==="user"?`### You \xB7 ${D(t.ts)}`:`### Secretary \xB7 ${D(t.ts)}`}

${t.text}`).join(`

---

`)}function rt({turns:r,thread:t}){let n=[...r].reverse().find(a=>a.role==="secretary")?.text||"";return(0,s.jsx)(e.Detail,{markdown:nt(r),navigationTitle:"Secretary \u2014 markdown",metadata:(0,s.jsxs)(e.Detail.Metadata,{children:[(0,s.jsx)(e.Detail.Metadata.Label,{title:"Turns",text:`${r.length}`}),t&&(0,s.jsx)(e.Detail.Metadata.Label,{title:"Thread",text:t})]}),actions:(0,s.jsxs)(e.ActionPanel,{children:[n&&(0,s.jsx)(e.Action.CopyToClipboard,{title:"Copy Last Reply",content:n}),t&&(0,s.jsx)(e.Action.OpenInBrowser,{title:"Open Thread in Vault View",url:`http://air.tail97979c.ts.net:8080/secretary/agent-output/conversations/${t}.md`})]})})}function V(r){let{question:t}=r.arguments,[n,a]=(0,o.useState)([{role:"user",text:t,ts:Date.now()}]),[l,A]=(0,o.useState)("connecting"),[c,m]=(0,o.useState)(!0),[b,C]=(0,o.useState)(null),[d,E]=(0,o.useState)(null),[M,P]=(0,o.useState)(null),[L,R]=(0,o.useState)(""),w=(0,o.useRef)(!1),I=(0,o.useRef)(!1),[H,_]=(0,o.useState)(0),{push:ot}=(0,e.useNavigation)(),h=(0,o.useCallback)(async(u,p)=>{m(!0),C(null),A("thinking"),P(null);let f=JSON.stringify(p?{text:u,thread_id:p}:{text:u}),T=null;for(let O of N)try{let g=new AbortController,y=await fetch(O,{method:"POST",headers:{"Content-Type":"application/json"},body:f,signal:g.signal});if(!y.ok||!y.body){T=`HTTP ${y.status} from ${O}`;continue}let q=y.body.getReader(),B=new TextDecoder,S="";for(;;){if(w.current){g.abort();return}let{value:J,done:Y}=await q.read();if(Y)break;S+=B.decode(J,{stream:!0});let F=S.split(`

`);S=F.pop()||"";for(let K of F){if(!K.trim())continue;let $="message",k="";for(let i of K.split(`
`))i.startsWith("event: ")?$=i.slice(7).trim():i.startsWith("data: ")&&(k=i.slice(6));if(!k)continue;let x;try{x=JSON.parse(k)}catch{continue}if($==="status"){let i=x.text;typeof i=="string"&&A(i)}else if($==="result"){let i=x;a(G=>[...G,{role:"secretary",text:i.reply||"(empty)",ts:Date.now()}]),i.thread&&E(i.thread),typeof i.duration_s=="number"&&P(i.duration_s),m(!1)}}}return}catch(g){T=String(g.message||g);continue}C(T||"all endpoints failed"),m(!1)},[]),j=(0,o.useCallback)(u=>{let p=u.trim();!p||c||(a(f=>[...f,{role:"user",text:p,ts:Date.now()}]),R(""),_(f=>f+1),h(p,d))},[c,h,d]);(0,o.useEffect)(()=>(w.current=!1,I.current||(I.current=!0,h(t,null)),()=>{w.current=!0}),[t,h]);let W=b?`[Network error]
${b}

Tried:
${N.map(u=>`  - ${u}`).join(`
`)}

Is Tailscale up? Is vault-view running on air?`:et(n,c?l:null);return(0,s.jsxs)(e.Form,{isLoading:c&&!b,navigationTitle:c?`Secretary \u2014 ${l}`:"Secretary",actions:(0,s.jsxs)(e.ActionPanel,{children:[(0,s.jsx)(e.Action.SubmitForm,{title:c?"Wait for Reply\u2026":"Send",icon:e.Icon.ArrowUp,onSubmit:u=>j(u.text||L)}),(0,s.jsx)(e.Action.Push,{title:"View as Markdown",icon:e.Icon.Document,shortcut:{modifiers:["cmd"],key:"m"},target:(0,s.jsx)(rt,{turns:n,thread:d})}),n.length>0&&(0,s.jsx)(e.Action.CopyToClipboard,{title:"Copy Last Reply",icon:e.Icon.Clipboard,content:[...n].reverse().find(u=>u.role==="secretary")?.text||"",shortcut:{modifiers:["cmd"],key:"c"}}),d&&(0,s.jsx)(e.Action.OpenInBrowser,{title:"Open Thread in Vault View",icon:e.Icon.Globe,url:`http://air.tail97979c.ts.net:8080/secretary/agent-output/conversations/${d}.md`,shortcut:{modifiers:["cmd"],key:"o"}})]}),children:[(0,s.jsx)(e.Form.Description,{title:"Conversation",text:W}),(0,s.jsx)(e.Form.TextArea,{id:"text",title:"Message",placeholder:c?`(${l}\u2026 please wait)`:"type a follow-up, then \u2318\u21B5 to send",value:L,onChange:R,autoFocus:!0,enableMarkdown:!0},`input-${H}`),M!==null&&!c&&(0,s.jsx)(e.Form.Description,{title:"Last reply",text:`${M}s \xB7 thread ${d||"?"}`})]})}
