
#preferred binding
set -g prefix C-b
# set -g prefix C-c # it seems I naturally press this often

# decrease escape time
set -sg escape-time 20
# source tmux
unbind r
bind r source-file '~/.config/tmux/tmux.conf'

# enable mouse
set -g mouse on

# for vim options
setw -g mode-keys vi

# more intuitive bindings, and keep directory
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# to work properly with neovim s-cr
# unbind Shift-Enter

# vim-like navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g default-terminal "screen-256color"

# change base index
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
# set-option -g remember-window on

# tmux plugins
set -g @plugin 'tmux-plugin/tpm'
set -g @plugin 'christoomey/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux/yank'
set -g @plugin 'xamut/tmux-spotify'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# powerline config
set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Georgina, Ontario"
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-show-fahrenheit false
set -g status-position top


# yanking options

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#to resurect neovim
set -g @resurrect-strategy-nvim 'session'

# automtically rename window
setw -g automatic-rename

run '~/.tmux/plugins/tpm/tpm'
